### ISSUE TITLE
Rewrite the README in English

### ISSUE THREAD

**Issue by rememberYou** [gquittet/DeminEmojis#2]
Thanks for `DeminEmojis`,

In order to improve the understanding of the application I thought we could use English for the main `README.md`, and create several other `README.md` for translation (_e.g._ `README.fr.md`, `README.it.md`, _etc._)

Also, I think that we need to call the application `DeminEmojis` instead of `DéminEmojis`. The accents are quite restrictive as an application name.

What do you think?

**Comment by gquittet** [comment]
It's a great idea. But the name in French of this game is DéminEmojis. The name in English is Emojisweeper.
